//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActiveJob
    {
        public int Id { get; set; }
        public Nullable<int> jobId { get; set; }
        public Nullable<int> staus { get; set; }
        public byte[] results { get; set; }
    }
}
